name: Build binaries

on:
  push:
    branches: [ "master" ]
    paths:
      - 'cmd/universe/**'
      - ".github/workflows/build-binaries.yml"

jobs:
  # Build each component in parallel
  #
  build_universe_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        working-directory: cmd/universe
        run: go mod download
      - name: Build universe
        working-directory: cmd/universe/cmd/daemon
        run: go build -o sphere-universe ./main.go
      - name: Upload universe binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: universe-binaries
          path: |
            cmd/universe/cmd/daemon/sphere-universe