name: Build binaries

on:
  push:
    branches: [ "master" ]
    paths:
      - 'cmd/universe/**'
      - ".github/workflows/build-binaries.yml"

jobs:
  # Build each component in parallel
  #
  build_binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ universe ]
        go-version: [1.23, 1.24]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        working-directory: cmd/universe
        run: go mod download
      - name: Build ${{ matrix.component }}
        working-directory: cmd/${{ matrix.component }}/cmd/daemon
        run: go build -o sphere-${{ matrix.component }} ./main.go
