name: Build binaries

on:
  push:
    branches: [ "master" ]
    paths:
      - 'cmd/universe/**'
      - ".github/workflows/build-binaries.yml"

jobs:
  # Build each component in parallel
  #
  build_universe_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        working-directory: cmd/universe
        run: go mod download
      - name: Build universe
        working-directory: cmd/universe/cmd/daemon
        run: go build -o sphere-universe ./main.go
      - name: Upload universe binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: universe-binaries
          path: |
            cmd/universe/cmd/daemon/sphere-universe

  build_ingestion_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        working-directory: data-ingestion/cmd/server
        run: go mod download
      - name: Build ingestion
        working-directory: data-ingestion/cmd/server
        run: go build -o sphere-ingestion ./main.go
      - name: Upload ingestion binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ingestion-binaries
          path: |
            data-ingestion/cmd/server/sphere-ingestion

  build_storage_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        working-directory: data-storage/cmd/server
        run: go mod download
      - name: Build storage
        working-directory: data-storage/cmd/server
        run: go build -o sphere-storage ./main.go
      - name: Upload ingestion binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storage-binaries
          path: |
            data-storage/cmd/server/sphere-storage

  build_management_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        working-directory: data-management/cmd/server
        run: go mod download
      - name: Build management
        working-directory: data-management/cmd/server
        run: go build -o sphere-management ./main.go
      - name: Upload ingestion binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: management-binaries
          path: |
            data-management/cmd/server/sphere-management

  

  # Create a release for the binaries
  #
  archive_binaries:
    runs-on: ubuntu-latest
    needs:
      - build_universe_binaries
      - build_ingestion_binaries
      - build_storage_binaries
      - build_management_binaries
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-binaries'
          merge-multiple: true
          path: dist/
      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphere-binaries.tar.gz
          path: |
            dist/*
