name: Docker Image CI

on:
  workflow_run:
    workflows: [ "Build binaries" ]
    types: [ completed ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set latest tag to environment variable
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Verify that image with latest tag does not exist
        id: check_image
        run: |
          if docker pull hyperplanenl/platform:${{ env.LATEST_TAG }}; then
            echo "Image with tag ${{ env.LATEST_TAG }} already exists. Skipping build."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "Image with tag ${{ env.LATEST_TAG }} does not exist. Proceeding with build."
            echo "skip_build=false" >> $GITHUB_ENV
          fi
      - name: Set up QEMU
        if: env.skip_build == 'false'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        if: env.skip_build == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: hyperplanenl/platform:${{ env.LATEST_TAG }}
          build-args: |
            SPHERE_VERSION=${{env.LATEST_TAG}}